#!/usr/bin/env bash
set -euo pipefail

ROOT="$(realpath "$(dirname "$0")/..")"

echo "=== AGENTS.md Generation Tests ==="
echo ""

passed=0
failed=0

check_has() {
  local desc="$1" expected="$2" actual="$3"
  if echo "$actual" | grep -qF "$expected"; then
    echo "  ✓ $desc"
    ((passed++)) || true
  else
    echo "  ✗ $desc"
    echo "    expected to find: $expected"
    ((failed++)) || true
  fi
}

check_not_has() {
  local desc="$1" unwanted="$2" actual="$3"
  if echo "$actual" | grep -qF "$unwanted"; then
    echo "  ✗ $desc"
    echo "    should NOT contain: $unwanted"
    ((failed++)) || true
  else
    echo "  ✓ $desc"
    ((passed++)) || true
  fi
}

check_match() {
  local desc="$1" pattern="$2" actual="$3"
  if echo "$actual" | grep -qE "$pattern"; then
    echo "  ✓ $desc"
    ((passed++)) || true
  else
    echo "  ✗ $desc"
    echo "    expected pattern: $pattern"
    ((failed++)) || true
  fi
}

# --- Test 1: JS fixture project ---
echo "AGENTS.md generation from JS fixture:"

JS_FIXTURE="$ROOT/tests/fixtures/unhealthy-project"
JS_OUT=$(bash "$ROOT/scripts/generate-agents-md.sh" "$JS_FIXTURE" 2>/dev/null || echo "SCRIPT_FAILED")

if [ "$JS_OUT" = "SCRIPT_FAILED" ]; then
  echo "  ✗ script failed to run on JS fixture"
  ((failed++)) || true
else
  check_has "contains generated-by header" "Generated by Thymus" "$JS_OUT"
  check_has "contains Architecture Rules heading" "## Architecture Rules" "$JS_OUT"
  check_match "contains language info" "(typescript|javascript)" "$JS_OUT"
  check_has "contains Import Boundaries section" "Import Boundaries" "$JS_OUT"
  check_has "contains MUST NOT" "MUST NOT" "$JS_OUT"
  check_has "contains Guidelines section" "Architectural Guidelines" "$JS_OUT"
fi

# --- Test 2: Healthy JS fixture ---
echo ""
echo "AGENTS.md generation from healthy JS fixture:"

HEALTHY_FIXTURE="$ROOT/tests/fixtures/healthy-project"
HEALTHY_OUT=$(bash "$ROOT/scripts/generate-agents-md.sh" "$HEALTHY_FIXTURE" 2>/dev/null || echo "SCRIPT_FAILED")

if [ "$HEALTHY_OUT" = "SCRIPT_FAILED" ]; then
  echo "  ✗ script failed to run on healthy fixture"
  ((failed++)) || true
else
  check_has "healthy: contains header" "Generated by Thymus" "$HEALTHY_OUT"
  check_has "healthy: contains Architecture Rules" "## Architecture Rules" "$HEALTHY_OUT"
  check_has "healthy: contains Guidelines" "Architectural Guidelines" "$HEALTHY_OUT"
fi

# --- Test 3: Idempotent output ---
echo ""
echo "Idempotent output:"

if [ "$JS_OUT" != "SCRIPT_FAILED" ]; then
  JS_OUT2=$(bash "$ROOT/scripts/generate-agents-md.sh" "$JS_FIXTURE" 2>/dev/null || echo "SCRIPT_FAILED")

  # Strip timestamps for comparison (they'll differ by seconds)
  STRIPPED1=$(echo "$JS_OUT" | grep -v "Last generated:")
  STRIPPED2=$(echo "$JS_OUT2" | grep -v "Last generated:")

  if [ "$STRIPPED1" = "$STRIPPED2" ]; then
    echo "  ✓ running twice produces identical output (excluding timestamp)"
    ((passed++)) || true
  else
    echo "  ✗ output differs between runs"
    ((failed++)) || true
  fi
else
  echo "  ~ skipped (JS fixture failed)"
fi

# --- Test 4: Output contains all three sections ---
echo ""
echo "Section structure:"

if [ "$JS_OUT" != "SCRIPT_FAILED" ]; then
  check_has "has architecture overview" "## Architecture Rules" "$JS_OUT"
  check_match "has boundary rules" "(Import Boundaries|Pattern Restrictions|Conventions)" "$JS_OUT"
  check_has "has semantic rules" "Architectural Guidelines" "$JS_OUT"
fi

# --- Test 5: Boundary rules from invariants appear as natural language ---
echo ""
echo "Rule translation:"

if [ "$JS_OUT" != "SCRIPT_FAILED" ]; then
  # The unhealthy project has a boundary-routes-no-db rule
  check_match "boundary rule appears in output" "(routes|db|MUST NOT|import)" "$JS_OUT"
fi

# --- Test 6: Import from AGENTS.md (reverse sync) ---
echo ""
echo "Reverse sync (import-agents-rules.sh):"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# Create a synthetic AGENTS.md
cat > "$TMPDIR/AGENTS.md" << 'EOF'
# Architecture

## Rules

- Files in `src/controllers/` must not import from `src/repositories/`
- The `axios` package should only be used in `src/lib/api-client`
- No raw SQL outside of `src/db/`
- Files in `src/routes` MUST NOT import `prisma`
EOF

IMPORT_OUT=$(bash "$ROOT/scripts/import-agents-rules.sh" "$TMPDIR" 2>/dev/null || echo "IMPORT_FAILED")

if [ "$IMPORT_OUT" = "IMPORT_FAILED" ]; then
  echo "  ✗ import script failed"
  ((failed++)) || true
else
  check_has "extracts boundary rule" "type: boundary" "$IMPORT_OUT"
  check_has "extracts source glob" "source_glob:" "$IMPORT_OUT"
  check_has "extracts forbidden import" "forbidden_imports:" "$IMPORT_OUT"
  check_has "extracts YAML format" "invariants:" "$IMPORT_OUT"
  check_has "has version" 'version: "1.0"' "$IMPORT_OUT"
fi

# --- Test 7: Import handles missing file gracefully ---
echo ""
echo "Edge cases:"

EMPTY_DIR=$(mktemp -d)
IMPORT_ERR=$(bash "$ROOT/scripts/import-agents-rules.sh" "$EMPTY_DIR" 2>&1 || true)
rm -rf "$EMPTY_DIR"

check_has "missing file: shows error" "No AGENTS.md or CLAUDE.md found" "$IMPORT_ERR"

echo ""
echo "Results: $passed passed, $failed failed"
[ "$failed" -eq 0 ] || exit 1
